package com.example.admin.chestionar;

public class Intrebari {
    public String intrebari[]={
            "Aud cuvintele in minte inainte de a le citi, rosti sau scrie. ",
             "Oamenii vin la mine sa ceara sfaturi, atat la locul de munca cat si acasa.",
             "Petrec timp in mod regulat meditand,reflectand si gandindu-ma la problemele importante ale vietii.",
              "Imi place sa fiu inconjurat de plante.",
             "Cand am o problema, caut ajutorul altcuiva mai degraba decat sa incerc s-o rezolv singur.",
              "Prefer cartile cu ilustratii multe.",
              "Am o voce placuta.",
               "Prefer sporturile de echipa celor care se practica individual.",
               "Trebuie sa exersez pentru a-mi forma o deprindere; nu ajunge sa citesc sau sa urmaresc o demonstratie.",
                "Aud intotdeauna o nota falsa.",
               "Ma simt mai bine cand lucrurile sunt masurate, clasificate, analizate, cuantificate.",
        "Adesea ma joc cu animalele.",
                "Cred ca am o coordonare motrica buna.",
        "Adesea bat ritmul sau fredonez cand lucrez sau invat ceva nou.",
                "Cartile sunt foarte importante pentru mine.",
                "Am participat la sesiuni si seminarii de consiliere si dezvoltare personala ca sa aflu mai multe despre mine insumi.",
                "Cand inchid ochii, vad adesea imagini clare.",
                "Am cel putin trei prieteni apropiati.",
                "Retin mai mult de la radio sau ascultand o caseta audio decat de la TV sau din filme.",
                "Imi place sa gasesc erori de logica in ceea ce spun sau fac ceilalti",
                "Tin un jurnal in care consemnez evenimentele din viata mea interioara.",
                "Imi plac jocurile ca: Scrabble, integrame, etc.",
                "Stiu multe melodii.",
                "Sunt patron sau cel putin m-am gandit serios sa incep o afacere proprie.",
                "Prefer sa-mi petrec serile cu prietenii decat sa stau singur.",
                "Pot sa-mi imaginez usor cum ar arata ceva vazut de sus.",
                "Daca aud o melodie o data sau de doua ori, pot s-o reproduc cu acuratete.",
                "Fac experimente cu plante si animale.",
                "Fac sport/activitati sportive in mod regulat.",
                "Imi place sa ma distrez pe mine si pe altii, cu rime sau cu jocuri de cuvinte.",
                "Ma consider lider (altii mi-au spus ca sunt lider.",
                "Sunt sensibil la culori.",
                "Mi-e greu sa stau nemiscat mai mult timp.",
                "Pot sa socotesc in minte cu usurinta.",
                "Cand lucrez imi place sa categorisesc lucrurile dupa importanta lor.",
                "Consider ca am vointa puternica si ca sunt independent.",
                "Matematica si stiintele au fost materiile mele preferate in scoala.",
                "Pot sa tin ritmul cu un instrument de percutie simplu cand se canta un cantec.",
                "Folosesc frecvent un aparat de fotografiat sau o camere video pentru a inregistra ceea ce vad in jur.",
                "Ceilalti imi cer cateodata sa explic sensul cuvintelor pe care le folosesc cand scriu sau cand vorbesc.",
                "Imi place sa port haine din materiale naturale.",
                "Sunt realist in privinta punctelor mele tari si slabe (datorita feedback-ului primit din diverse surse.",
                        "Cele mai bune idei imi vin cand ma plimb,fac jogging sau desfasor o activitate fizica.",
                        "Prefer sa joc Monopoly sau bridge decat sa fac pasiente sau sa joc alte jocuri de unul singuri.",
                        "Ascult frecvent muzica la radio, casetofon, etc.",
                        "Visez mult noaptea.",
                        "Ca elev, am invatat mai usor la engleza, stiinte sociale si istorie decat la matematica si stiinte.",
                        "Prefer sa petrec un week-end singur la o cabana in padure,decat intr-o statiune moderna cu multa lume in jur",
                        "Imi place sa cos, sa tes, sa cioplesc, sa fac tamplarie sau alte activitati manuale.",
                        "Cateodata ma surprind mergand pe strada fredonand.",
                        "Ma orientez usor in locuri necunoscute.",
                        "Cand conduc pe autostrada sunt mai atent la ce scrie pe pancarte decat la peisaj.",
                        "Ma simt bine in padure.",
                        "Imi place sa joc jocuri care necesita gandire logica.",
                        "Simt nevoia sa ating obiectele pentru a afla mai multe despre ele.",
                        "Imi place sa desenez sau sa mazgalesc.",
                        "Imi place sa-i invat pe altii (indivizi sau grupuri) ceea ce stiu eu sa fac.",
                        "Imi place sa ma implic in activitati legate de munca mea, biserica sau comunitate care presupun prezenta unui numar mare de oameni.",
                        "Imi place sa fac experimente (ex.” Ce-ar fi daca as dubla cantitatea de apa pe care o torn la radacina trandafirului in fiecare zi?”)",
                        "Pot sa raspund la atacuri cu argumente.",
                        "Cant la un instrument muzical.",
                        "La scoala geometria mi s-a parut mai usoara decat algebra.",
                        "Mintea mea cauta structuri, regularitati, secvente logice in jur.",
                        "Recent am scris ceva ce m-a facut sa ma simt mandru sau a fost apreciat de ceilalti.",
                        "Weekend-ul ideal este o iesire in natura.",
                        "Ma simt bine in mijlocul multimii.",
                        "Cred ca aproape orice are o explicatie rationala.",
                        "Am un hobby pe care nu-l dezvalui altora.",
                        "Prefer sa-mi petrec timpul liber in natura.",
                        "Ma intereseaza progresele in stiinta.",
                        "Sunt foarte bun bucatar.",
                        "Imi place sa ma joc cu jocuri de puzzle, labirint si alte jocuri vizuale.",
                        "Folosesc frecvent gesturi sau alte forme de limbaj corporal cand vorbesc cu altii.",
                        "Viata mea ar fi mai saraca daca nu ar fi muzica.",
                        "Uneori gandesc in concepte clare, abstracte, pe care nu le formulez in cuvinte sau imagini.",
                        "Conversatia mea face apel frecvent la lucruri pe care le-am citit sau le-am auzit.",
                        "Am cateva scopuri importante in viata, la care ma gandesc in mod regulat.",
                        "In camera mea trebuie sa fie o floare.",
                        "Imi place “Montagne russe”(roller coaster) si alte experiente fizice asemanatoare."
    };
    public int num[]={1,6,7,8,6,3,5,6,4,5,2,8,4,5,1,7,3,6,1,2,7,1,5,7,6,3,5,8,4,1,6,3,4,2,
                      8,7,2,5,3,1,8,7,4,6,5,5,1,7,4,5,3,1,8,2,4,3,6,6,2,7,5,3,2,1,8,6,2,7,4,2,8,3,4,5,2,1,7,8,4};
    public int[] contor=new int[55];
    public String mesaje[]={
            "a",
            "Inteligenta lingvistica: reprezinta usurinta in exprimarea şi perceperea nuantelor limbajului verbal, abilitatea de a invata limbi straine si de a folosi limbajul in atingerea unor obiective dar si abilitatea de a folosi eficient limbajul pentru a te exprima teoretic si poetic. Persoanele care poseda acest tip de inteligena prefera discutiile, dezbaterile, asociatiile de cuvinte, sa citeasca, sa scrie, sa povesteasca. Domeniile de performanta pentru persoanele care au inteligneta lingvisitca sunt : jurnalismul, literatura, psihologia, justitia.",
            "Inteligenta logico-matematică presupune capacitatea de a elabora rationamente, de a recunoaste si folosi scheme şi relatii abstracte. Persoanele de acest tip prefera numerele, structurile, formulele, tehnologia, conceptele matematice, abstractizarile, rationamentele si devin, de obicei, contabili, matematicieni, chimisti, fizicieni.",
            "Inteligenta spatiala presupune capacitatea de a gandi în imagini, de a-si reprezenta în imagini informaţiile. Persoanele care au inteligenta spatiala pot intelege si reprezenta foarte bine lumea spatial-vizuala, au simtul orientarii in spatiu si memorie vizuala foarte buna. Aceste persoane invata folosind imagini, observand, efectuand reprezentari grafice, prefera sa deseneze, sa construiasca, sa modeleze, sa proiecteze, prefera culorile, imaginile, sa efectueze schite, scheme. Domeniile de performantă sunt proiectarea, arhitectura, artele plastice.",
            "Inteligenta chinestezica implica utilizarea cu eficienta a miscarilor corporale, abilitatea mentala de a coordona miscarile corpului, fizicul si mentalul aflandu-se in stransa legatura. Persoanele  care au inteligenta chinestezica învata prin implicare directa, manevrare de obiecte, activitati practice, miscare. Domenii de performanta: sport, dans, activitati practice.",
            "Inteligenta muzicala reprezinta abilitatea de a recunoaste si de a gandi in sunete, ritmuri, melodii şi rime, a fi sensibil la ton, la intensitatea, inaltimea si timbrul sunetului, abilitatea de a recunoaste, crea şi reproduce muzica, folosind un instrument sau vocea. Implica ascultare activa şi presupune o legatura puternica intre muzica si emotii. Este specifică cantaretilor, muzicienilor, dansatorilor.",
            "Inteligenta interpersonala se refera la intelegerea celorlalti si te ajuta sa fii sociabil. Persoanele care poseda astfel de intelienta, prefera sa socializeze si sa empatizeze cu grupuri de persoane, se implica în activitati comune, sunt buni organizatori, au talent in privinta comunicarii şi negocierii, prefera interactiunea, colaborarea, relatiile sociale. Sunt preocupati de a intelege intentiile, motivatiile si dorintele altora, aceasta inteligenta usurandu-le colaborarea cu cei din jur.  Profesii care solicita acest tip de inteligenta sunt: profesor, avocat, psiholog, asistent social, journalist, stiinte umaniste si sociale.",
            "Inteligenta intrapersonala se refera la intelegerea propriei persoane. Aceasta inteligenta o intalnim la persoanele introspective, care au capacitatea de se intelege pe ei insisi, de a-si analiza propriile emotii, ganduri, temeri, motivatii. Aceste persoane isi formeaza o imagine clara, reala despre ele insele si inteleg propriile sentimente, si le foosesc pentru ghidarea comportamentului. Persoanele de acest gen au un puternic simt al identitatii, sunt increzatori in fortele proprii. Domenii de performanta: cercetare, literatura, filozofie, munca stiintifica, teologie, psihologie.",
            "Inteligenta naturistă are de a face cu observarea, înţelegerea şi organizarea modelelor în mediul natural.Persoanele care posedă acest tip de inteligenţă au capacitatea de conectare cu alte ființe vii, inclusiv cu plantele și animalele. Sunt preocupate de poluarea mediului înconjurător, iubesc animalele de casă (adoptă), pasionate de natură, adoră grădinăritul, se simt vii atunci când intră în contact direct cu natura, percep natura mai presus de celelalte lucruri, cunoscătoare în ale vremii, pot face predicţii meteorologice. Casa lor este mereu curată, ecologică. De asemenea, recunosc foarte rapid plantele şi animalele, le clasifică şi le studiază în detaliu. De mici sunt capabile să sorteze și să clasifice cu pricepere pietre, insecte, scoici ori dinozauri de aceea vei găsi la ele ierbare profesionist aranjate, păsări şi animăluţe de tot felul. Reţin cu uşurinţă denumirile latine ale speciilor studiate. Au capacități de observare, colectare, clasificare șicalificare ce pot fi aplicate și în mediul „uman”. Pasionaţi de cărţi ce abordează subiecte naturiste, fie ele reale ori SF. Cariere posibile: conservatorist, grădinar, fermier, îngrijitor sau antrenor de animale, poliţist de circulaţie, om de ştiinţă, cercetător în domeniul agriculturii, pădurar, botanist, florar, oceanograf, speolog, îngrijitor zoo, biolog marin, ecologist, arhitect naturist, vindecător sau vraci (medicină naturistă ori tradiţională), homeopat, meteorolog, muzeograf în muzee ce expun plante, animale sau roci, arhivar, bibliotecar, inginer, mecanic, criminalist."
    };
    public Intrebari(){
        for (int i=0;i<=30;i++) contor[i]=0;
    }
    public String getQuestion(int nr)
    {
        return intrebari[nr];
    }
}
